name: Experiment
on: 
  #schedule:
   # - cron: '*/15 * * * *'
   # - cron: '30 2 * * *'
   push

jobs:
  job1:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    
    - name: List files
      run: echo "hii"
    - name: Step 7 - download the artifact from build
      uses: jfrog/setup-jfrog-cli@v2
    - run: |
         jfrog --version
         jf config add
         
