name: Experiment
on: 
  schedule:
  # - cron: '*/15 * * * *'
    - cron: '30 2 * * *'

jobs:
  job1:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    
    - name: List files
      run: echo "hii"
